import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const balooFont = localFont({
  src: "./fonts/BalooPaaji2-VariableFont_wght.ttf",
  variable: "--font-baloo",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${balooFont.variable}  antialiased`}>{children}</body>
    </html>
  );
}
